### PR TITLE
RELATED: FET-157 Upgrade Typescript

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yanlipnican** [comment]
Did you update to latest typescript or is `3.3.4000` any specific?

**Comment by yanlipnican** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-merge-compliance-check/9/ : SUCCESS in 23s

**Pull request merged**
