### PR TITLE
SPACE-2660 Add copyright and top-level README

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-merge-compliance-check/41/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-fossa-scanning-zuul/6/ : SUCCESS in 27s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-sonarqube-scan-zuul-gate/19/ : SUCCESS in 23s

**Pull request merged**
