### PR TITLE
RELATED: FET-564 Sonar config

### PR DESCRIPTION
**Pull request by ivanmjartan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gdc-js-style-check-extended-sonar-PR57

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-sonarqube-scan-zuul-el7/1/ : SUCCESS in 36s (non-voting)

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gdc-js-style-gate-PR57

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-merge-compliance-check/21/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-fossa-scanning-zuul-el7/3/ : SUCCESS in 11s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gdc-js-style-sonarqube-scan-zuul-el7/2/ : SUCCESS in 32s (non-voting)

**Pull request merged**
